2009-01-27 04:30 UTC+0100 Przemyslaw Czerpak (druzus/at/priv.onet.pl)   * harbour/include/hbdefs.h     * added some C compilers which supports stdint.h
  * harbour/source/common/hbprintf.c
    * eliminated non portable GCC only C syntax.
    * updated to compile with other C compilers.
      Now only GNUC with C99 support and BORLAND C gives all
      +inf/-inf/NaN values for [long] double conversions.
      Other compilers uses NaN also for infinite numbers or nothing.
      Please add full support for them. See TODO notes I left.
      For compilers which supports C99 floating point macros should
      be enough to enable the same macros used for GNUC && _ISOC99_SOURCE.

  * harbour/contrib/hbcrypt/sha2.h
  * harbour/contrib/hbcrypt/sha2.c
    ! fixed BCC5.5 compilation

   TOFIX: harbour/contrib/hbssl/ssl.c[631], sslctx.c[268], sslctx.c[281]
          error: invalid conversion from ‘void*’ to ‘const char*’
          I do not know if SSL_get_ex_data()/SSL_CTX_get_app_data()
          returns valid ASCIIZ string so I cannot decide if simple casting
          is safe and to pacify above errors.
          Viktor, can you look at it?


git-svn-id: https://harbour-project.svn.sourceforge.net/svnroot/harbour-project/trunk@10119 ef52b332-12a4-b543-bf59-08b57769829b