2009-03-31 11:46 UTC+0200 Viktor Szakats (harbour.01 syenar hu)   * INSTALL     * Moved Windows CE compilers into a separate section.
  * bin/hb-mkdyn.bat
    * Changes made to allow wce arch. (provision for wce arch)

  * mpkg_win.bat
    * Allows to override HB_ARCHITECTURE. (provision for wce arch)
    + Include arch in target directory. (provision for wce arch)

  * include/hbatomic.h
    - Turned off inline asm for _MSC_VER compilers in 64-bit mode. (pocc64, msvc64)
      These target don't support inline asm.
      This fixes previously reported regressions with these targets.

  * utils/hbmk2/hbmk2.prg
    % win/owatcom: Pentium Pro scheduling.
    * win/owatcom: Temply set back stack calling convention.

  * external/libhpdf/Makefile
    - Disabled for pocc64 due to errors, even internal compiler error:
      ---
      can't spill register variable: rcx (3) image
      ../../hpdf_image.c(480): fatal error: Internal error: best_spillee.
      ---

  * config/win/bcc.cf
    + Added comment about -4, -5, -6.

  * ChangeLog
    ! Minor fix to prev entry.



git-svn-id: https://harbour-project.svn.sourceforge.net/svnroot/harbour-project/trunk@10750 ef52b332-12a4-b543-bf59-08b57769829b