2009-04-08 10:22 UTC+0200 Viktor Szakats (harbour.01 syenar hu)   * INSTALL     * Cross build text fixed to be multiplatform.
  * contrib/rddsql/sddfb/Makefile
    ! Excluded for msvc64:
      ../../fbirddd.c(187) : warning C4244: 'argument' : conversion from 'ULONG' to 'short', possible loss of data
      ../../fbirddd.c(231) : warning C4244: 'argument' : conversion from 'ISC_STATUS' to 'USHORT', possible loss of data
      ../../fbirddd.c(241) : warning C4244: 'argument' : conversion from 'ISC_STATUS' to 'USHORT', possible loss of data
      ../../fbirddd.c(249) : warning C4244: 'argument' : conversion from 'ISC_STATUS' to 'USHORT', possible loss of data
      ../../fbirddd.c(265) : warning C4244: 'argument' : conversion from 'ISC_STATUS' to 'USHORT', possible loss of data
      ../../fbirddd.c(409) : error C2440: '=' : cannot convert from 'isc_stmt_handle' to 'void *'
              Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
      ../../fbirddd.c(410) : error C2440: '=' : cannot convert from 'isc_tr_handle' to 'void *'
              Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
      ../../fbirddd.c(446) : error C2664: 'isc_dsql_free_statement' : cannot convert parameter 2 from 'void **' to 'isc_stmt_handle *'
              Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
      ../../fbirddd.c(451) : error C2664: 'isc_rollback_transaction' : cannot convert parameter 2 from 'void **' to 'isc_tr_handle *'
              Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
      ../../fbirddd.c(469) : error C2664: 'isc_dsql_fetch' : cannot convert parameter 2 from 'void **' to 'isc_stmt_handle *'
              Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
      ../../fbirddd.c(531) : error C2664: 'isc_dsql_free_statement' : cannot convert parameter 2 from 'void **' to 'isc_stmt_handle *'
              Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
      ../../fbirddd.c(533) : warning C4244: 'argument' : conversion from 'ISC_STATUS' to 'USHORT', possible loss of data
      ../../fbirddd.c(538) : error C2664: 'isc_commit_transaction' : cannot convert parameter 2 from 'void **' to 'isc_tr_handle *'
              Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
      ../../fbirddd.c(540) : warning C4244: 'argument' : conversion from 'ISC_STATUS' to 'USHORT', possible loss of data



git-svn-id: https://harbour-project.svn.sourceforge.net/svnroot/harbour-project/trunk@10817 ef52b332-12a4-b543-bf59-08b57769829b