2010-01-16 15:28 UTC+0100 Viktor Szakats (harbour.01 syenar.hu)   * external/libpng/LICENSE   * external/libpng/Makefile   * external/libpng/png.c   * external/libpng/png.h   * external/libpng/pngrio.c   * external/libpng/pngerror.c   * external/libpng/pngconf.h   * external/libpng/pngwrite.c   * external/libpng/pngset.c   * external/libpng/pngpread.c   * external/libpng/pngwtran.c   * external/libpng/pngwio.c   * external/libpng/pngrutil.c   * external/libpng/pngwutil.c   * external/libpng/pngread.c   * external/libpng/pngmem.c   * external/libpng/pngget.c   * external/libpng/pngrtran.c   * external/libpng/pngtrans.c   - external/libpng/pngvcrd.c   - external/libpng/pnggccrd.c   + external/libpng/pngpriv.h     * Updated to 1.4.0 (from 1.2.40)
  * external/libpng/Makefile
    + Added -DPNG_NO_SETJMP for watcom builds to prevent these errors
      from happening:
         wcc386   -zq -bt=nt -bm -w0 -6s -fp6 -onaehtr -s -ei -zp4 -zt0 -oi -i. -i..\..\..\..\..\include -IF:\work\harbour\harbour\external\zlib -DUSE_FAR_KEYWORD -fo=pngread.obj  ..\..\..\pngread.c
         ..\..\..\pngread.c(86): Error! E1071: Type of parameter 2 does not agree with previous definition
         ..\..\..\pngread.c(86): Note! N2003: source conversion type is 'void (__watcall *)(unsigned int __p1[],int __p2)'
         ..\..\..\pngread.c(86): Note! N2004: target conversion type is 'void (__cdecl *)(unsigned int __p1[],int __p2)'
         wcc386   -zq -bt=nt -bm -w0 -6s -fp6 -onaehtr -s -ei -zp4 -zt0 -oi -i. -i..\..\..\..\..\include  -IF:\work\harbour\harbour\external\zlib  -fo=pngwrite.obj  ..\.
         .\..\pngwrite.c
         ..\..\..\pngwrite.c(507): Error! E1071: Type of parameter 2 does not agree with previous definition
         ..\..\..\pngwrite.c(507): Note! N2003: source conversion type is 'void (__watcall *)(unsigned int __p1[],int __p2)'
         ..\..\..\pngwrite.c(507): Note! N2004: target conversion type is 'void (__cdecl *)(unsigned int __p1[],int __p2)'

  * external/sqlite3/sqlite3.c
  * external/sqlite3/sqlite3.h
    + sqlite upgraded to 3.6.22 (from 3.6.21)



git-svn-id: https://harbour-project.svn.sourceforge.net/svnroot/harbour-project/trunk@13612 ef52b332-12a4-b543-bf59-08b57769829b