2009-12-07 10:14 UTC+0100 Viktor Szakats (harbour.01 syenar.hu)   * external/libpng/pngerror.c   * external/libpng/pngrio.c   * external/libpng/pngwrite.c   * external/libpng/pngconf.h   * external/libpng/pngwtran.c   * external/libpng/pngpread.c   * external/libpng/pngset.c   * external/libpng/LICENSE   * external/libpng/pngwio.c   * external/libpng/pngrutil.c   * external/libpng/pngwutil.c   * external/libpng/pngread.c   * external/libpng/pngmem.c   * external/libpng/png.c   * external/libpng/pngget.c   * external/libpng/pnggccrd.c   * external/libpng/png.h   * external/libpng/pngrtran.c   * external/libpng/pngtrans.c     ! Reverted to 1.2.40 (from 1.2.41)       Due to this regression:       ---       wcc386   -zq -bt=nt -bm -w0 -3s -i. -i../../../../../include -d2 -DHB_TR_LEVEL_DEBUG  -I/home/ice/w/xhb/hbci/harbour-build/external/zlib  -fo=pngmem.obj  ../../../pngmem.c       ../../../pngmem.c(447): Error! E1057: Modifiers disagree with previous definition of 'png_calloc'       ../../../pngmem.c(447): Note! I2002: 'png_calloc' defined in: ../../../png.h(3754)       ---
git-svn-id: https://harbour-project.svn.sourceforge.net/svnroot/harbour-project/trunk@13152 ef52b332-12a4-b543-bf59-08b57769829b